<a href="https://colab.research.google.com/github/jonfisik/Projects/blob/master/python/AlgebraLinearPython/2MatrizesPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Matrizes

In [8]:
'''Matriz 2 x 2'''
A = np.array([[2,-1],[0,4]])
A

array([[ 2, -1],
       [ 0,  4]])

In [11]:
A.shape # retorna a propriedade da dimansão da matriz

(2, 2)

In [14]:
'''Matriz 2 x 3'''
B = np.array([[1,0,-4],[4,-3,2]])
B

array([[ 1,  0, -4],
       [ 4, -3,  2]])

In [15]:
B.shape

(2, 3)

In [16]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
C.shape

(3, 3)

In [ ]:
# Matrizes - representação 2 (função np.matrix())

In [ ]:
?np.matrix

In [ ]:
C = np.matrix('1 2; 3 4')
C

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(C)

numpy.matrix

In [ ]:
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(C)

numpy.matrix

In [ ]:
# Tipos de matrizes no python


In [ ]:
'''Matriz linha'''
L1 = np.array([3,4,5])
L1

array([3, 4, 5])

In [ ]:
L2 = np.array([[3,4,6]]) 
L2

array([[3, 4, 6]])

In [ ]:
L3 = np.array([[0,0,0,0]])
L3

array([[0, 0, 0, 0]])

In [ ]:
L1.shape # vetor

(3,)

In [ ]:
L2.shape # matriz

(1, 3)

In [ ]:
L3.shape # matriz

(1, 4)

In [ ]:
''' Matriz coluna'''
C1 = np.array([[1],[3],[7]]) # cada colchete é uma linha. E cada casa depois da virgula uma coluna
C1

array([[1],
       [3],
       [7]])

In [ ]:
C1.shape # (linha,coluna)

(3, 1)

In [ ]:
C2 = np.array([[0],[0],[0],[0]])
C2

array([[0],
       [0],
       [0],
       [0]])

In [ ]:
''' Matriz nula '''
N = np.zeros([2,2]) # função zeros
N

array([[0., 0.],
       [0., 0.]])

In [ ]:
?np.zeros

In [ ]:
N1 = np.zeros((2,2)) # paranteses
N1

array([[0., 0.],
       [0., 0.]])

In [ ]:
N2 = np.zeros([5,5]) # colchetes
N2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
''' Matriz diagonal'''
D = np.diag([1,2,3,6,5]) # elementos da diagonal principal
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
D.shape

(5, 5)

In [ ]:
E = np.diag([1,1,1,1]) # Matriz identidade
E

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
E.shape

(4, 4)

In [ ]:
F = np.diag((1,1,1))
F

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
F.shape

(3, 3)

In [ ]:
'''Matriz identidade'''
I = np.eye(4,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
I.shape

(4, 4)

In [ ]:
I1 = np.eye(7)
I1

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
I1.shape

(7, 7)

In [ ]:
?np.eye

In [ ]:
I2 = np.eye(2) # O elemento é real
I2

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Transposição de matrizes

In [ ]:
S = np.array([[1,4,3],[4,2,5],[3,5,0]])
A = np.array([[1,2,3,6],[9,7,4,6]])
B = np.array([[8,5,3,3],[1,0,1,8]])

In [ ]:
''' método para transpor matrizes np.transpose(matriz) '''

' método para transpor matrizes np.transpose(matriz) '

In [ ]:
S # S é simétrica

array([[1, 4, 3],
       [4, 2, 5],
       [3, 5, 0]])

In [ ]:
np.transpose(S)

array([[1, 4, 3],
       [4, 2, 5],
       [3, 5, 0]])

In [ ]:
A

array([[1, 2, 3, 6],
       [9, 7, 4, 6]])

In [ ]:
np.transpose(A)

array([[1, 9],
       [2, 7],
       [3, 4],
       [6, 6]])

In [ ]:
B

array([[8, 5, 3, 3],
       [1, 0, 1, 8]])

In [ ]:
np.transpose(B)

array([[8, 1],
       [5, 0],
       [3, 1],
       [3, 8]])

In [ ]:
''' método para transpor matrizes matriz.T '''
A.T

array([[1, 9],
       [2, 7],
       [3, 4],
       [6, 6]])

In [ ]:
B.T

array([[8, 1],
       [5, 0],
       [3, 1],
       [3, 8]])

In [ ]:
 ''' Testando propriedade da transposição de matrizes '''

In [ ]:
# i) Simetria de matrizes
np.array_equal(S,S.T)

True

In [ ]:
# ii) Transposta da transposta
np.array_equal(A.T.T, A)

True

In [ ]:
# iii) Soma de transposta
np.array_equal((A+B).T, A.T+B.T)

True

In [ ]:
# iv) transposta de uma matriz multipplicada por um escalar
k = 2
np.array_equal((k*B).T, k*(B.T))

True

In [ ]:
# Slicing de matrizes - indexação de matrizes - parte 1

In [18]:
A = np.array([[2,4,6],[4,7,1],[9,3,8]])

In [19]:
A

array([[2, 4, 6],
       [4, 7, 1],
       [9, 3, 8]])

In [20]:
''' retorna a dimensão da matriz '''
A.shape

(3, 3)

In [21]:
''' Slicing - fatiamento'''
A[:]

array([[2, 4, 6],
       [4, 7, 1],
       [9, 3, 8]])

In [23]:
''' Slincing Alternativo'''
A[:,:]

array([[2, 4, 6],
       [4, 7, 1],
       [9, 3, 8]])

In [24]:
A[1,:] # linha 1 e todas as colunas

array([4, 7, 1])

In [25]:
A[2,:] # linha 1 e todas as colunas

array([9, 3, 8])

In [26]:
A[:,0] # Coluna 0 e todas as linhas

array([2, 4, 9])

In [37]:
A[1,1] # um elemento, linha 1 coluna 1

7

In [39]:
A[2,1] # Linha 3 coluna 2 - Em python linha 2 coluna 1

3

In [40]:
J = A # J é uma referência de A e não uma cópia

In [41]:
J

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3,  8]])

In [42]:
J[0,2] = 19 # Alterar valor da matriz J

In [43]:
J

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3,  8]])

In [45]:
A # A matriz "A" tbm é alterada

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3,  8]])

In [46]:
# Cópia de matrizes

In [47]:
G =J.copy()

In [49]:
G # Cópia da matriz "J"

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3,  8]])

In [50]:
G[2,2] = 63

In [51]:
G

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3, 63]])

In [53]:
J # A matriz não foi alterada 

array([[ 2,  4, 19],
       [ 4,  7,  1],
       [ 9,  3,  8]])

In [54]:
F = J[:,1] # todos os elementos da coluna 1

In [55]:
F

array([4, 7, 3])

In [66]:
''' Slicing parte 2'''
W = np.array([[0,3,2,6,5],[5,6,8,7,6],[9,5,6,1,0],[9,7,4,6,3]])
W

array([[0, 3, 2, 6, 5],
       [5, 6, 8, 7, 6],
       [9, 5, 6, 1, 0],
       [9, 7, 4, 6, 3]])

In [70]:
W.shape

(4, 5)

In [75]:
W1 = W[0,1:5] # Em python linha 0 e colunas de 1 a 4
W1

array([3, 2, 6, 5])

In [84]:
W2 = W[:,4] # Em python linhas de 0 a 3 e coluna 4
W2

array([5, 6, 0, 3])

In [86]:
W3 = W[1,1:5]
W3

array([6, 8, 7, 6])

In [89]:
W4 = W[1:4,2]
W4

array([8, 6, 4])