<a href="https://colab.research.google.com/github/jonfisik/Projects/blob/master/2MatrizesPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
# Matrizes

In [21]:
'''Matriz 2 x 2'''
A = np.array([[2,-1],[0,4]])
A

array([[ 2, -1],
       [ 0,  4]])

In [22]:
'''Matriz 2 x 3'''
B = np.array([[1,0,-4],[4,-3,2]])
B

array([[ 1,  0, -4],
       [ 4, -3,  2]])

In [23]:
# Matrizes - representação 2 (função np.matrix())

In [24]:
?np.matrix

In [25]:
C = np.matrix('1 2; 3 4')
C

matrix([[1, 2],
        [3, 4]])

In [26]:
type(C)

numpy.matrix

In [27]:
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [28]:
type(C)

numpy.matrix

In [11]:
# Tipos de matrizes no python


In [30]:
'''Matriz linha'''
L1 = np.array([3,4,5])
L1

array([3, 4, 5])

In [35]:
L2 = np.array([[3,4,6]]) 
L2

array([[3, 4, 6]])

In [36]:
L3 = np.array([[0,0,0,0]])
L3

array([[0, 0, 0, 0]])

In [32]:
L1.shape # vetor

(3,)

In [37]:
L2.shape # matriz

(1, 3)

In [38]:
L3.shape # matriz

(1, 4)

In [40]:
''' Matriz coluna'''
C1 = np.array([[1],[3],[7]]) # cada colchete é uma linha. E cada casa depois da virgula uma coluna
C1

array([[1],
       [3],
       [7]])

In [41]:
C1.shape # (linha,coluna)

(3, 1)

In [43]:
C2 = np.array([[0],[0],[0],[0]])
C2

array([[0],
       [0],
       [0],
       [0]])

In [44]:
''' Matriz nula '''
N = np.zeros([2,2]) # função zeros
N

array([[0., 0.],
       [0., 0.]])

In [ ]:
?np.zeros

In [45]:
N1 = np.zeros((2,2)) # paranteses
N1

array([[0., 0.],
       [0., 0.]])

In [47]:
N2 = np.zeros([5,5]) # colchetes
N2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
''' Matriz diagonal'''
D = np.diag([1,2,3,6,5]) # elementos da diagonal principal
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 5]])

In [59]:
D.shape

(5, 5)

In [60]:
E = np.diag([1,1,1,1]) # Matriz identidade
E

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [61]:
E.shape

(4, 4)

In [62]:
F = np.diag((1,1,1))
F

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [63]:
F.shape

(3, 3)

In [64]:
'''Matriz identidade'''
I = np.eye(4,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
I.shape

(4, 4)

In [67]:
I1 = np.eye(7)
I1

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [69]:
I1.shape

(7, 7)

In [71]:
?np.eye

In [74]:
I2 = np.eye(2) # O elemento é real
I2

array([[1., 0.],
       [0., 1.]])

In [75]:
# Transposição de matrizes

In [76]:
S = np.array([[1,4,3],[4,2,5],[3,5,0]])
A = np.array([[1,2,3,6],[9,7,4,6]])
B = np.array([[8,5,3,3],[1,0,1,8]])

In [77]:
''' método para transpor matrizes np.transpose(matriz) '''

' método para transpor matrizes np.transpose(matriz) '

In [80]:
S # S é simétrica

array([[1, 4, 3],
       [4, 2, 5],
       [3, 5, 0]])

In [81]:
np.transpose(S)

array([[1, 4, 3],
       [4, 2, 5],
       [3, 5, 0]])

In [82]:
A

array([[1, 2, 3, 6],
       [9, 7, 4, 6]])

In [83]:
np.transpose(A)

array([[1, 9],
       [2, 7],
       [3, 4],
       [6, 6]])

In [84]:
B

array([[8, 5, 3, 3],
       [1, 0, 1, 8]])

In [85]:
np.transpose(B)

array([[8, 1],
       [5, 0],
       [3, 1],
       [3, 8]])

In [86]:
''' método para transpor matrizes matriz.T '''
A.T

array([[1, 9],
       [2, 7],
       [3, 4],
       [6, 6]])

In [87]:
B.T

array([[8, 1],
       [5, 0],
       [3, 1],
       [3, 8]])

In [ ]:
 ''' Testando propriedade da transposição de matrizes '''

In [88]:
# i) Simetria de matrizes
np.array_equal(S,S.T)

True

In [89]:
# ii) Transposta da transposta
np.array_equal(A.T.T, A)

True

In [90]:
# iii) Soma de transposta
np.array_equal((A+B).T, A.T+B.T)

True

In [92]:
# iv) transposta de uma matriz multipplicada por um escalar
k = 2
np.array_equal((k*B).T, k*(B.T))

True

In [ ]:
# Slicing de matrizes - indexação de matrizes - parte 1

In [ ]:
A = np.array([[2,4,6],[4,7,1],[9,3,8]])

In [ ]:
A

In [ ]:
''' retorna a dimensão da matriz '''
A.shape

In [ ]:
''' Slicing - fatiamento'''
A[:]

In [ ]:
A[:,:]

In [ ]:
A[1,:] # linha 1 e todas as colunas

In [ ]:
A[2,:] # linha 1 e todas as colunas

In [ ]:
A[:,0] # Coluna 0 e todas as linhas

In [ ]:
A[1,1] # um elemento, linha 1 coluna 1

In [ ]:
J = A # J é uma referência de A e não uma cópia

In [ ]:
J

In [ ]:
J[0,2] = 19 # Alterar valor damatriz J

In [ ]:
J

In [13]:
A # A matriz A tbm é alterada

array([[ 2, -1],
       [ 0,  4]])

In [14]:
# Cópia de matrizes

In [15]:
G =J.copy()

NameError: ignored

In [16]:
G

NameError: ignored

In [ ]:
G[2,2] = 63

In [17]:
G

NameError: ignored

In [ ]:
J

In [18]:
F = J[:,1] # todos os elementos da coluna 1

NameError: ignored

In [ ]:
F