<a href="https://colab.research.google.com/github/jonfisik/Projects/blob/master/python/AlgebraLinearPython/4DeterminantePython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,4],[5,3,-1],[7,2,0]])
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [ ]:
det_A = np.linalg.det(A)

In [ ]:
det_A

-56.00000000000002

In [ ]:
?np.linalg.det

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [ ]:
from numpy.linalg import det

In [ ]:
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [ ]:
det(A)

-56.00000000000002

In [ ]:
B = np.array([[1,2,4,5,6,7],[5,3,-1,5,1,2],[7,2,0,1,4,9],[1,2,1,5,6,5],[-7,2,4,-1,6,6],[0,2,5,5,9,7]])

In [ ]:
B.shape

(6, 6)

In [ ]:
det(B)

8184.000000000006

In [10]:
''' Propriedade dos determinantes '''
import numpy as np
from numpy.linalg import det

In [11]:
A = np.array(([1,2,4],[5,3,-1],[7,2,0]))
Az = np.zeros([3,3])

In [12]:
# Matriz A
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [13]:
# Matriz
Az

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 1) det(Az) = 0
det(Az)

0.0

In [16]:
# 2) det(A) = det(A.T)
det(A)

-56.00000000000002

In [17]:
det(A.T)

-55.99999999999997

In [19]:
det(A) == det(A.T)

False

In [23]:
# Se B = k*A[0,:], det(B) = k*det(A)
k = 3
B = A.copy()
B[0,:] = k*B[0,:]
B

array([[ 3,  6, 12],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [24]:
det(B)

-167.99999999999997

In [26]:
k*det(A)

-168.00000000000006

In [27]:
det(B) == k*det(A)

False

In [29]:
# 4) Se trocarmos a posição de duas linhas e det muda de sinal
L1 = A[0,:] # linha 1
L2 = A[1,:] # linha 2
L3 = A[2,:] # linha 3

In [31]:
C = np.array([L2,L1,L3])
C

array([[ 5,  3, -1],
       [ 1,  2,  4],
       [ 7,  2,  0]])

In [32]:
det(C)

56.00000000000002

In [33]:
det(A)

-56.00000000000002

In [35]:
# 5) Matrizes com duas linhas iguais -> det = 0
D = np.array([L1,L1,L2])
D

array([[ 1,  2,  4],
       [ 1,  2,  4],
       [ 5,  3, -1]])

In [36]:
det(D)

0.0

In [40]:
# 6) det(A+B) != det(A) + det(B)
A = np.array(([1,2,4],[5,3,-1],[7,2,0]))
B = np.array(([0,5,4],[8,2,1],[9,-2,3]))
np.array_equal(det(A+B),det(A)+det(B))

False

In [41]:
det(A+B)

-897.9999999999995

In [42]:
det(A) + det(B)

-266.9999999999999

In [43]:
# 7) det(A.dot(B)) = det(A)*det(B)
det(A.dot(B))

11815.999999999996

In [44]:
det(A)*det(B)

11815.999999999996