<a href="https://colab.research.google.com/github/jonfisik/Projects/blob/master/3EscalonamentoPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  

In [44]:
M = np.array([[1,4,3,1],[2,5,4,4],[1,-3,-2,5]])
M

array([[ 1,  4,  3,  1],
       [ 2,  5,  4,  4],
       [ 1, -3, -2,  5]])

In [45]:
M[1,:] = -2*M[0,:] + M[1,:]
M

array([[ 1,  4,  3,  1],
       [ 0, -3, -2,  2],
       [ 1, -3, -2,  5]])

In [46]:
M[2,:] = -1*M[0,:] + M[2,:]
M

array([[ 1,  4,  3,  1],
       [ 0, -3, -2,  2],
       [ 0, -7, -5,  4]])

In [47]:
M[1,:] = -1/3*M[1,:]
M

array([[ 1,  4,  3,  1],
       [ 0,  1,  0,  0],
       [ 0, -7, -5,  4]])

In [48]:
M[0,:] = -4*M[1,:] + M[0,:]
M

array([[ 1,  0,  3,  1],
       [ 0,  1,  0,  0],
       [ 0, -7, -5,  4]])

In [49]:
M[2,:] = 7*M[1,:] + M[2,:]
M

array([[ 1,  0,  3,  1],
       [ 0,  1,  0,  0],
       [ 0,  0, -5,  4]])

In [50]:
M[2,:] = -3*M[2,:]
M

array([[  1,   0,   3,   1],
       [  0,   1,   0,   0],
       [  0,   0,  15, -12]])

In [51]:
M[1,:] = -1/3*M[2,:] + M[1,:]
M

array([[  1,   0,   3,   1],
       [  0,   1,  -5,   4],
       [  0,   0,  15, -12]])

In [52]:
M[0,:] = -1/3*M[2,:] + M[0,:]
M

array([[  1,   0,  -2,   5],
       [  0,   1,  -5,   4],
       [  0,   0,  15, -12]])

In [53]:
print(M)

[[  1   0  -2   5]
 [  0   1  -5   4]
 [  0   0  15 -12]]
